# permissions for end users to edit notesapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: notesapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: notes-operator
    app.kubernetes.io/part-of: notes-operator
    app.kubernetes.io/managed-by: kustomize
  name: notesapp-editor-role
rules:
- apiGroups:
  - notes.notes.com
  resources:
  - notesapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notes.notes.com
  resources:
  - notesapps/status
  verbs:
  - get
